### ISSUE TITLE
Crash upon connect with node >= 0.11.12

### ISSUE THREAD

**Issue by jbnicolai** [sidorares/node-vim-debugger#17]
Running the latest quote-unquote stable version of node I get an error and crash upon launching `vim-inspector.js`. 

Using the kick ass [`n`](https://github.com/visionmedia/n) to narrow down the breaking version, it seems that it was introduced in `0.11.12`, `0.11.13` being the latest stable.

The output upon connecting is:
```bash
$ ./bin/vim-inspector.js
start vim with "vim -nb" command or type :nbs within vim
> /Users/jbnicolai/projects/personal/node-vim-debugger/node_modules/tmp/lib/tmp.js:260
  throw err;
        ^
TypeError: Property 'prompt' of object #<REPLServer> is not a function
    at REPLServer.displayPrompt (repl.js:397:8)
    at VimConnection.showScript (/Users/jbnicolai/projects/personal/node-vim-debugger/lib/vim-connection.js:180:7)
    at /Users/jbnicolai/projects/personal/node-vim-debugger/lib/vim-connection.js:128:10
    at Client._onResponse (/Users/jbnicolai/projects/personal/node-vim-debugger/node_modules/v8-debugger/lib/client.js:135:5)
    at Protocol.execute (/Users/jbnicolai/projects/personal/node-vim-debugger/node_modules/v8-debugger/lib/protocol.js:86:14)
    at Client.<anonymous> (/Users/jbnicolai/projects/personal/node-vim-debugger/node_modules/v8-debugger/lib/client.js:49:14)
    at Client.EventEmitter.emit (events.js:104:17)
    at readableAddChunk (_stream_readable.js:156:16)
    at Client.Readable.push (_stream_readable.js:123:10)
    at TCP.onread (net.js:520:20)
```

`0.10.31` all the way through `0.11.11` seem to work though.

**Comment by calvinchengx** [comment]
I was trying out `node-vim-debugger` today but ran into this problem too. Unfortunately, broken from 0.11.12 onwards. :(

**Comment by sidorares** [comment]
@jbnicolai @calvinchengx - should be fixed now. Could you test it with node? ( I only tested with iojs 1.5.1 ) Published as v0.2.2

**Comment by calvinchengx** [comment]
This works.  So it was just about making `repl` use its `setPrompt()` method in the latest nodejs repl APIs. Thanks!!!

**Comment by sidorares** [comment]
unfortunately the only documented function is `repl.start()` - https://nodejs.org/api/repl.html
While module is marked as stable this means that any of other functions could break in the future

**Comment by calvinchengx** [comment]
Yup. Understood. But at least I know where to start looking when something breaks now. :-D

**Comment by sidorares** [comment]
@calvinchengx I encourage you read source code and add something from 'nice to have' list of features :) Don't have much time for it and it's in "nearly useful" state over last year
